apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-viewer-binding
  namespace: green
subjects:
- kind: User
  name: test-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: service-viewer-role
  apiGroup: rbac.authorization.k8s.io

